#!/usr/bin/env ruby

top_level = File.expand_path(File.join(File.dirname(__FILE__),".."))
$: << File.join(top_level,"lib")
$: << File.join(top_level,"ext")

require 'libtom/math'
require 'benchmark'

p = 1_000_000
puts "Calculating powers of 2"
Benchmark.bm(35) do |x|
    x.report("  Ruby  ::Bignum 2**#{p}") { 2**p }
    x.report("  LibTom::Bignum 2**#{p}") { LibTom::Math::two_to_the(p) }
end

puts
puts "A series of meaningless multiplications"
ltm_1 = LibTom::Math::Bignum(9)**25
ruby_1 = 9**25
[1000,10_000,100_000].each do |power|
    Benchmark.bm(35) do |x|
        x.report("  Ruby  ::Bignum (9**25)**(#{power})") { ruby_1**power }
        x.report("  LibTom::Bignum (9**25)**(#{power})") { ltm_1**power  }
    end
    puts
end




