#!/usr/bin/env ruby

$: << "../lib"
$: << "../ext"

require 'libtom/math'
require 'mathn'
require 'benchmark'

n = ARGV.shift.to_i

mathn_prime = Prime.new
tom_prime   = LibTom::Math::Prime.new

Benchmark.bm(25) do |x|
    x.report("Mathn  #{n} primes") { n.times { mathn_prime.succ } }
    x.report("LibTom #{n} primes") { n.times { tom_prime.succ   } }
end
