#!/usr/bin/env ruby

top_level = File.expand_path(File.join(File.dirname(__FILE__),".."))
$: << File.join(top_level,"lib")
$: << File.join(top_level,"ext")

require 'libtom/math'
require 'mathn'
require 'benchmark'

n = ARGV.shift.to_i

mathn_prime = Prime.new
tom_prime   = LibTom::Math::Prime.new

Benchmark.bm(25) do |x|
    x.report("Mathn  #{n} primes") { n.times { mathn_prime.succ } }
    x.report("LibTom #{n} primes") { n.times { tom_prime.succ   } }
end
